version: 2.1
jobs:
  test:
    docker:
      - image: postman/newman:alpine
    steps:
      - checkout
      - run:
          name: Run Postman Tests
          command: newman run postman/collection.json
workflows:
  test-workflow:
    jobs:
      - test
